language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd esperanto-analyzer-react
  - yarn install
  - yarn install jest-cli
  - yarn test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  on:
    branch: development
